version: "3.9"
   
services:
  api:
    build: 
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./backend:/app
    ports:
      - "8008:8008"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"