name: backend checks
on:
  push:
    paths:
      - "backend/**"
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: backend-${{ hashFiles('**/requirements.txt') }}
          restore-keys: backend-${{ hashFiles('**/requirements.txt') }}

      - name: Install PyRight
        run: make up

      - name: Typecheck
        run: make format
