name: backend checks
on:
  push:
    paths:
      - "backend/**"
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Set up
        uses: docker-compose up
