name: backend checks
on:
  push:
    paths:
      - "backend/**"
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up
        run: docker-compose up
