name: Main Push

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: yarn

      - name: build
        run: yarn build

      - name: check build
        run: node checkBundleSize.js > bundleSize.json && cat bundleSize.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundleSize
          path: frontend/bundleSize.json
