name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: see size
        run: cat frontend/buildSize.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildSize
          path: |
            **/buildSize.json

      - name: change name
        run: mv frontend/buildSize.json frontend/buildSize2.json

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: buildSize

      - name: see size
        run: cat frontend/buildSize2.json

      - name: ls
        run: ls frontend

      - name: compare
        run: node frontend/compare.js
