name: backend checks
on:
  push:
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install PyRight
        run: npm i pyright -g
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Typecheck
        run: pyright
      - name: Run black --check .
        run: black --check --exclude db/migrations .
